### ISSUE TITLE
Issue getting up and running

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/idv-test#14]
Hi @julienchastang - I updated my local git repo and ran the command `docker-compose up -d`, but it looks like only one test runs:

~~~
$ docker-compose up -d
Creating network "idvtest_default" with the default driver
Pulling web (nginx:latest)...
latest: Pulling from library/nginx
2a72cbf407d6: Pull complete
fefa2faca81f: Pull complete
080aeede8114: Pull complete
Digest: sha256:c4ee0ecb376636258447e1d8effb56c09c75fe7acf756bf7c13efadf38aa0aca
Status: Downloaded newer image for nginx:latest
Creating idv-test ... done
Creating idvtest_web_1      ... done
~~~

If I attach to the docker container, I do not see any activity. Am I missing something? The `test-output` directory is totally empty. Thanks!

FYI - I am running this as we are looking at switching over from motherlode to our new atm machine to host thredds.ucar.edu.

**Comment by julienchastang** [comment]
Alrighty. Let me look into it.

**Comment by julienchastang** [comment]
Hi Sean. A few thoughts:

- Updating with `git` is good b/c you get the latest `docker-compose.yml`, but also do a `docker pull unidata/idv-test:latest` and a `docker pull nginx` to make sure those are up-to-date.
- Also I wonder if there is a permissions problem going on. The `docker-compose.yml` is referencing a couple of directories on the docker host (your local system) so make sure those are available before starting the container:  `mkdir logs/ test-output/` (and owned by you) in the directory that is local to the `docker-compose.yml`.
- Finally, I cannot recall if I tested this on macOS Docker (and I can't at this point since I am on my crappy home network, and won't be back until after Spring Break), but there may be an issue there. I have this container running presently on Jetstream even serving the results with nginx to the web. If you want to give me your public key, you can run it from there.

Hope this helps

**Comment by julienchastang** [comment]
It is done running now, FYI: http://149.165.169.172/compare.html

**Comment by lesserwhirls** [comment]
Looks like I just needed to update the idv-test container with a pull. Thanks @julienchastang!

**Comment by lesserwhirls** [comment]
I was able to run against both thredds.ucar.edu and atm.ucar.edu - no major differences, so this gives me some confidence in moving to our new server (new hardware, still 4.6). Thanks for the work on this @julienchastang!

**Comment by julienchastang** [comment]
Cool. I'm glad it worked for you. It is not the most user friendly utility (e.g., endless log messages), but still hopefully provides something useful.
